# HTMLProofer Configuration
# This file tells HTMLProofer to ignore certain known false positives
# while still catching real issues

# Ignore empty anchor tags on line 1 (these are from the Chirpy theme navigation)
# and focus on real content issues

# Run with: bundle exec htmlproofer _site --ignore-files "/404.html/" --ignore-empty-alt --ignore-missing-alt --disable-external
