theme: jekyll-theme-chirpy
lang: en
timezone: Australia/Darwin

title: Spearlink Cyber
tagline: Strengthening Cybersecurity through Excellence in Practice
description: >
  Professional cybersecurity consultant specialising in penetration testing, cloud security review, 
  and security consulting services. Supporting Australian organisations with practical 
  security assessment and strategic guidance, with particular focus on Northern Territory clients.

url: "https://spearlinkcyber.com.au"

webmaster_verifications:
  google:
  bing:

analytics:
  google:
    id:

pageviews:
  provider:

theme_mode: light
cdn:
avatar: /assets/img/logos/spearlink-main.png
social_preview_image: /assets/img/logos/spearlink-horizontal.png
toc: false

comments:
  provider:

assets:
  self_host:
    enabled: true

pwa:
  enabled: true
  cache:
    enabled: true

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
      toc: false

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - _disabled
  - _posts
