theme: jekyll-theme-chirpy
lang: en
timezone: Australia/Darwin

title: Spearlink Cyber
tagline: Precision, Excellence, Collaboration.
description: >
  Professional cybersecurity consultant specialising in penetration testing, cloud security review, 
  and security consulting services. Supporting Australian organisations with practical 
  security assessment and strategic guidance, with particular focus on Northern Territory clients.

url: "https://spearlinkcyber.com.au"

# Author/Social Configuration (fixes footer empty anchor tags)
social:
  name: Spearlink Cyber
  email: sales@spearlinkcyber.com.au
  links:
    - https://www.linkedin.com/company/spearlink-cyber

# Footer copyright name
author: Spearlink Cyber

webmaster_verifications:
  google: qcUWvVhnFbK2olYDS9bW-7_6KVxV8gk9KZxB2MIT-50
  bing: # Add your Bing Webmaster verification code

analytics:
  google:
    id: G-XXXXXXXXXX  # Replace with your Google Analytics ID

pageviews:
  provider: google

theme_mode: light
cdn:
avatar: /assets/img/logos/spearlink-main.png
social_preview_image: /assets/img/logos/spearlink-horizontal.png
toc: false

comments:
  provider:

assets:
  self_host:
    enabled: true

pwa:
  enabled: true
  cache:
    enabled: true

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
      toc: false

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - _disabled
  - sitemap.xml.backup
  - robots.txt.backup
